# --- General options --- #
# url is the full website URL
# baseurl is the website's URL without the hostname

# If you are building a simple GitHub user page (http://username.github.io) then use these settings:
url: "https://www.infernux.no"
baseurl: ""

# Name of website
title: infernux' blog

# Short description of your site
description: security by obscurity

# --- Navigation bar options --- #

# List of links in the navigation bar
navbar-links:
  Guides:
    - Practical Hacking: PracticalHacking
  Archive: Archive
  About Me: "aboutme"
avatar: "/img/avatar-icon.png"

author:
  name: Truls
  email: YmxvZ0BpbmZlcm51eC5ubw==
  github: infernuxmonster
  twitter: infernuxmonster

footer-links-active:
  rss: false
  facebook: false
  email: false
  twitter: true
  google-plus: false
  github: true
  reddit: false
  linkedin: true
  xing: false
  stackoverflow: false
  snapchat: false
  instagram: false
  youtube: false
  spotify: false
  telephone: false
share-links-active:
  twitter: true
  facebook: false
  google: false
  linkedin: false


# --- Misc --- #
# Fill in your Disqus shortname (NOT the userid) if you want to support Disqus comments
disqus: ""

# Fill in your Google Analytics ID to track your website using GA
google_analytics: "UA-125990163-1"


excerpt_length: 50
title-separator: "-"
timezone: Europe/Berlin
markdown: kramdown
highlighter: rouge
permalink: "/:year-:month-:day-:title/"
paginate: 5
kramdown:
  input: GFM

defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    comments: true
    social-share: true
- scope:
    path: ''
  values:
    layout: page
    show-avatar: true
link-tags: false
exclude:
  - CHANGELOG.md
  - CNAME
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - Vagrantfile
prose:
  rooturl: _posts
  media: img
  ignore:
  - 404.html
  - LICENSE
  - feed.xml
  - _config.yml
  - "/_layouts"
  - "/_includes"
  - "/css"
  - "/img"
  - "/js"
  metadata:
    _posts:
    - name: layout
      field:
        element: hidden
        value: post
    - name: title
      field:
        element: text
        label: Post title
        placeholder: Title
        alterable: true
    - name: subtitle
      field:
        element: textarea
        label: Subtitle
        placeholder: A description of your post.
        alterable: true
    - name: date
      field:
        element: text
        label: Date
        help: Enter date of post.
        placeholder: yyyy-mm-dd
        alterable: true
    - name: image
      field:
        element: text
        label: Image
        help: Add a thumbnail image to your post.
        placeholder: Thumbnail
        alterable: true
    - name: published
      field:
        element: checkbox
        label: Publish
        help: Check to publish post, uncheck to hide.
gems:
- jekyll-paginate
- jekyll-mentions
- jemoji
#- jekyll-crosspost-to-medium
